services:
  - type: web
    name: promptly-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PORT
        value: 10000
      - key: ENVIRONMENT  
        value: production
      - key: DATABASE_URL
        sync: false # You'll set this manually in Render dashboard
